name: Key Discovery
description: Request supporting evidence for newly discovered key to be added to the registry
title: "Key proofs needed for key ID: Name (0000 0000 0000 0000)"
labels: ["valid key proofs needed"]
body:
  - type: input
    id: name
    attributes:
      label: Name of Key Holder
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Home page URL for key holder
    validations:
      required: false
  - type: textarea
    id: purpose
    attributes:
      label: Please describe the intended use of this key (i.e. verifying signatures on releases for named software product, personal, messaging signing, etc.) 
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Copy of armored public key (-----BEGIN PGP PUBLIC KEY BLOCK-----)
    validations:
      required: true
  - type: textarea
    id: refs
    attributes:
      label: List of external references vouching for this public key (URLs + description, 1 per line)
    validations:
      required: true

