# This is a basic workflow to help you get started with Actions
name: Schema Validation

# Controls when the workflow will run
on:
  pull_request:
    types: [ "opened", "reopened", "synchronize" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Identity Assertions
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
            
      # You may pin to the exact commit or the version.
      # uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7
      - name: schema-validation-action
        uses: cardinalby/schema-validator-action@3.1.1
        with:
          # Schema file path or URL
          schema: 'schema.json'
          # | separated files to validate. Globs are allowed
          file: 'registry/*.json'
          # | separated list of parsers used to parse the file: json, yaml
          fileParser: json
          # schemasafe validation mode: default, lax, strong
          mode: default
          # schemas for resolving refs, JSON object: id -> file/url
          # refSchemasMap: 
          # schemas for resolving refs, JSON array of file/url strings
          # refSchemasArray: 
          # strip unknown features from the schema
          fixSchemas: true

      - name: jq-install
        run: sudo apt-get install jq

      - name: registry-checks
        run: bash registry-checks.sh