name: Deploy static HTML

on:
  # Assumes all pre-merge workflows have completed successfully via branch protection
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Initialize site root related /dist (displace if exists)
        run: |
          [ -d ./html/dist ] && mv ./html/dist ./.html-dist
          mkdir -p ./html/dist

      - uses: actions/download-artifact@v4
        with:
          name: registry-dist
          path: ./html/dist/
          
      - name: Configure GH pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./html

      - name: Deploy GH pages
        id: deployment
        uses: actions/deploy-pages@v4
